### ISSUE TITLE
Util HTML parse error

### ISSUE THREAD

**Issue by alokhan** [nylas/sync-engine#148]
Hi,

Here is a small error when parsing message in the function handle_charref : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/generic.py", line 190, in _run
    fail_classes=self.retry_fail_classes)
  File "/home/alo/git/inbox/inbox/util/concurrency.py", line 120, in retry_and_report_killed
    **reset_params)()
  File "/home/alo/git/inbox/inbox/util/concurrency.py", line 73, in wrapped
    return func(*args, **kwargs)
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/generic.py", line 217, in _run_impl
    self.state = self.state_handlers[old_state]()
  File "/home/alo/git/inbox/inbox/util/concurrency.py", line 73, in wrapped
    return func(*args, **kwargs)
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/generic.py", line 270, in initial_sync
    self.initial_sync_impl(crispin_client)
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/generic.py", line 317, in initial_sync_impl
    self.download_uids(crispin_client, download_stack)
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/generic.py", line 403, in download_uids
    [uid])
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/generic.py", line 507, in download_and_commit_uids
    raw_messages, self.create_message)
  File "/home/alo/git/inbox/inbox/mailsync/backends/base.py", line 135, in create_db_objects
    uid = msg_create_fn(db_session, acc, folder, msg)
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/generic.py", line 433, in create_message
    msg)
  File "/home/alo/git/inbox/inbox/mailsync/backends/imap/common.py", line 260, in create_imap_message
    body_string=msg.body)
  File "/home/alo/git/inbox/inbox/models/message.py", line 225, in create_from_synced
    msg.calculate_body()
  File "/home/alo/git/inbox/inbox/models/message.py", line 352, in calculate_body
    self.snippet = self.calculate_html_snippet(html_part)
  File "/home/alo/git/inbox/inbox/models/message.py", line 362, in calculate_html_snippet
    text = strip_tags(text)
  File "/home/alo/git/inbox/inbox/util/html.py", line 61, in strip_tags
    s.feed(html)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 114, in feed
    self.goahead(0)
  File "/usr/local/lib/python2.7/HTMLParser.py", line 188, in goahead
    self.handle_charref(name)
  File "/home/alo/git/inbox/inbox/util/html.py", line 45, in handle_charref
    self.fed.append(unichr(val))
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
<CondstoreFolderSyncEngine at 0x3d6ba50> failed with ValueError

```

This looks like a python error so might be a pain to solve :)

http://wordaligned.org/articles/narrow-python

**Comment by emfree** [comment]
Thanks for the report! You probably want to be using a wide Python build. But this can still happen when parsing bad HTML, and is handled in 69d2f94.
