### ISSUE TITLE
Gmail account with multiple Important folders doesn't sync

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#156]
The following account

```
In [85]: conn.list_folders()
Out[85]:
[
 # ...
 (('\\HasNoChildren',), '/', u'Important'),
 # ...
 (('\\Important', '\\HasNoChildren'), '/', u'[Gmail]/Important'),
 # ...
]
```

results in the following traceback:

```
 Traceback (most recent call last):
	  File "/home/ubuntu/inbox/inbox/util/concurrency.py", line 73, in wrapped
    return func(*args, **kwargs)
	  File "/home/ubuntu/inbox/inbox/mailsync/backends/imap/monitor.py", line 145, in sync
    self.start_new_folder_sync_engines(folders)
	  File "/home/ubuntu/inbox/inbox/mailsync/backends/imap/monitor.py", line 90, in start_new_folder_sync_engines
    new_folders = [f for f in self.prepare_sync() if f not in folders]
	  File "/home/ubuntu/inbox/inbox/util/concurrency.py", line 73, in wrapped
    return func(*args, **kwargs)
	  File "/home/ubuntu/inbox/inbox/mailsync/backends/imap/monitor.py", line 73, in prepare_sync
    remote_folders, db_session)
	  File "/home/ubuntu/inbox/inbox/mailsync/backends/base.py", line 90, in save_folder_names
    folder = Folder.find_or_create(db_session, account, name)
	  File "/home/ubuntu/inbox/inbox/models/folder.py", line 76, in find_or_create
    obj = q.one()
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2395, in one
    ret = list(self)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2437, in __iter__
    self.session._autoflush()
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 132, in execute
    result = self._query(query)
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 271, in _query
    conn.query(q)
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 726, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 861, in _read_query_result
    result.read()
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1064, in read
    first_packet = self.connection._read_packet()
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 826, in _read_packet
    packet.check_error()
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 370, in check_error
    raise_mysql_exception(self._data)
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 116, in raise_mysql_exception
    _check_mysql_exception(errinfo)
	  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 109, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
	IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) (1062, u"Duplicate entry '634-important' for key 'namespace_id'") 'INSERT INTO tag (created_at, updated_at, deleted_at, namespace_id, public_id, name) VALUES (%s, %s, %s, %s, %s, %s)' (datetime.datetime(2015, 6, 10, 8, 18, 3, 114078), datetime.datetime(2015, 6, 10, 8, 18, 3, 114085), None, 634, 'aabhmscud1sf4xq6kxvugh209', u'important')
```

**Comment by thomasst** [comment]
Possibly related to https://github.com/nylas/sync-engine/issues/136

**Comment by kav-ya** [comment]
Thanks for the report!
Yes - as with #136, the problem is due to incorrect assumptions in the `CrispinClient.folder_names()` function. We're reimplementing how we map these flags to folder names; stay tuned.

**Comment by grinich** [comment]
Fixed!
