### ISSUE TITLE
Errors in DeleteHandler

### ISSUE THREAD

**Issue by thomasst** [nylas/sync-engine#167]
I've been getting errors like the following for a specific account:

```
Traceback (most recent call last):
	  File "/home/ubuntu/inbox/inbox/util/concurrency.py", line 73, in wrapped
    return func(*args, **kwargs)
	  File "/home/ubuntu/inbox/inbox/mailsync/gc.py", line 53, in _run_impl
    self.check(current_time)
	  File "/home/ubuntu/inbox/inbox/mailsync/gc.py", line 72, in check
    thread.messages.remove(message)
	AttributeError: 'NoneType' object has no attribute 'messages'
```

```
Traceback (most recent call last):
	  File "/home/ubuntu/inbox/inbox/util/concurrency.py", line 73, in wrapped
    return func(*args, **kwargs)
	  File "/home/ubuntu/inbox/inbox/mailsync/gc.py", line 53, in _run_impl
    self.check(current_time)
	  File "/home/ubuntu/inbox/inbox/mailsync/gc.py", line 72, in check
    thread.messages.remove(message)
	  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/collections.py", line 1066, in remove
    fn(self, value)
	ValueError: list.remove(x): x not in list
```

I am not sure how this exactly works, but would a fix like in https://github.com/elasticsales/inbox/commit/cf1717cfee6b72455c7381f8a2e9e4b1bf8bc81f be appropriate?

**Comment by grinich** [comment]
Do you have a good way to reproduce this? It kind of looks like delete requests are being made on objects have have been changes, or messages which have already been removed.

**Comment by thomasst** [comment]
Unfortunately not. I've been running Nylas with the described fix and haven't had any issues since.
