### ISSUE TITLE
[CANNOT] Mailbox isn't a valid mbox file from notmuch/xapian info

### ISSUE THREAD

**Issue by arthurlutz** [nylas/sync-engine#215]
I'm having trouble gettin sync-engine to work with my self-hosted imap/smtp setup. Here is one of the tracebacks that seems to be a problem.

```
Traceback (most recent call last):
	  File "/vagrant/inbox/util/concurrency.py", line 46, in wrapped
    return func(*args, **kwargs)
	  File "/vagrant/inbox/mailsync/backends/imap/generic.py", line 261, in initial_sync
    crispin_client.select_folder(self.folder_name, uidvalidity_cb)
	  File "/vagrant/inbox/crispin.py", line 295, in select_folder
    folder, readonly=self.readonly)
	  File "/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py", line 407, in select_folder
    self._command_and_check('select', self._normalise_folder(folder), readonly)
	  File "/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py", line 983, in _command_and_check
    self._checkok(command, typ, data)
	  File "/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py", line 989, in _checkok
    self._check_resp('OK', command, typ, data)
	  File "/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py", line 959, in _check_resp
    raise self.Error('%s failed: %r' % (command, data[0]))
	error: select failed: "[CANNOT] Mailbox isn't a valid mbox file"
``` 
from the following error 

```

[INFO] {"account_id": 1, "timestamp": "2015-10-11T20:57:45.859302Z", "module": "inbox.crispin:206", "greenlet_id": 92476432, "event": "Connection broken with error; retrying with new connection", "exception": "Traceback (most recent call last):\n\t  File \"/vagrant/inbox/util/concurrency.py\", line 46, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/vagrant/inbox/mailsync/backends/imap/generic.py\", line 261, in initial_sync\n    crispin_client.select_folder(self.folder_name, uidvalidity_cb)\n\t  File \"/vagrant/inbox/crispin.py\", line 295, in select_folder\n    folder, readonly=self.readonly)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 407, in select_folder\n    self._command_and_check('select', self._normalise_folder(folder), readonly)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 983, in _command_and_check\n    self._checkok(command, typ, data)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 989, in _checkok\n    self._check_resp('OK', command, typ, data)\n\t  File \"/usr/local/lib/python2.7/dist-packages/imapclient/imapclient.py\", line 959, in _check_resp\n    raise self.Error('%s failed: %r' % (command, data[0]))\n\terror: select failed: \"[CANNOT] Mailbox isn't a valid mbox file\"\n", "level": "info", "state": "initial", "provider": "custom", "folder": ".notmuch/xapian/position.baseB"}
[ERROR] {"greenlet_id": 92476432, "state": "initial", "account_id": 1, "provider": "custom", "timestamp": "2015-10-11T21:01:04.904615Z", "folder": ".notmuch/xapian/position.baseB", "error": "select failed: \"[CANNOT] Mailbox isn't a valid mbox file\"", "event": "IMAPClient error selecting folder. May be deleted", "module": "inbox.crispin:308", "level": "error"}

```

**Comment by grinich** [comment]
`[CANNOT] Mailbox isn't a valid mbox file` is being returned when the sync engine attempts to select a folder. I think this is an issue with your IMAP server or local mailbox setup, not the sync engine. The sync engine does nothing with mbox files.

**Comment by spang** [comment]
Closing this as unrelated to the sync engine.

**Comment by arthurlutz** [comment]
Sure, I figured a way to remove the undesired files from my mailbox and the traceback disappeared (thanks @grinich for the answer). But I still think that a traceback should not appear in the logs and should be caught by sync-engine.

**Comment by grinich** [comment]
It's just printed to the console. The traceback is also included in the JSON logs for analysis.
