### ISSUE TITLE
Build Errors: KeyError: 3 in bin/create-db and python/shell mismatch in setup.sh

### ISSUE THREAD

**Issue by michaelrommel** [nylas/sync-engine#217]
When building sync-engine in vagrant, I get the following errors:

* when setup.sh runs python bin/create-db:
``` 
Stamping with alembic revision
Traceback (most recent call last):
  File "bin/create-db", line 80, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "bin/create-db", line 74, in main
    alembic.command.stamp(alembic_cfg, "head")
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 355, in stamp
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 82, in <module>
    run_migrations_online()
  File "migrations/env.py", line 65, in run_migrations_online
    engine = engine_manager.engines[shard_id]
KeyError: 3
```
This happens with the version of alembic in requirements.txt and also with the current version 0.8.2

* setup.sh then tries to run `python bin/create-test-db` but this is a shell script, not python.

**Comment by emfree** [comment]
Whoops -- these should be fixed in 15ff86f and 8e50c40.
