### ISSUE TITLE
Angular.js issue in accounts page

### ISSUE THREAD

**Issue by etagwerker** [nylas/sync-engine#311]
Hello, 

I recently signed up for an account in https://developer.nylas.com/console but I found this issue in my Chrome console: 

```
angular.js:10126Error: [$interpolate:interr] http://errors.angularjs.org/1.2.28/$interpolate/interr?p0=Account%20Provide…%7D&p1=TypeError%3A%20Cannot%20read%20property%20'charAt'%20of%20undefined
    at Error (native)
    at https://developer.nylas.com/static/js/vendor/angular/angular.min.js:6:450
    at Object.p (https://developer.nylas.com/static/js/vendor/angular/angular.min.js:80:480)
    at h.$digest (https://developer.nylas.com/static/js/vendor/angular/angular.min.js:110:238)
    at h.$apply (https://developer.nylas.com/static/js/vendor/angular/angular.min.js:113:362)
    at m (https://developer.nylas.com/static/js/vendor/angular/angular.min.js:72:454)
    at w (https://developer.nylas.com/static/js/vendor/angular/angular.min.js:77:463)
    at XMLHttpRequest.B.onreadystatechange (https://developer.nylas.com/static/js/vendor/angular/angular.min.js:79:24)
```

This is my environment: Chrome  51.0.2704.84 (64-bit) on Mac OS X 10.11.5 

I'm not sure what could be wrong. The page shows up correctly and my newly added account shows up as Running.

**Comment by grinich** [comment]
Closing due to stale and can't reproduce.
