### ISSUE TITLE
setup.sh fails during pip setup

### ISSUE THREAD

**Issue by davidcelis** [nylas/sync-engine#317]
I'm trying to set up the sync engine on a DigitalOcean droplet (Ubuntu 16.04 x64) and end up getting the following error:

```
$ sudo -H ./setup.sh

      _   _       _
     | \ | |_   _| | __ _ ___
     |  \| | | | | |/ _' / __|
     | |\  | |_| | | (_| \__ \
     |_| \_|\__, |_|\__,_|___/
            |___/

     This script installs dependencies for the Nylas Sync Engine.

     For more details, visit:
     https://www.github.com/nylas/sync-engine

Updating packages...
MySQL Exists. Not adding upstream mysql package
W: http://repo.mysql.com/apt/ubuntu/dists/precise/InRelease: Signature by key A4A9406876FCBD3C456770C88C718D3B5072E1F5 uses weak digest algorithm (SHA1)
Installing dependencies from apt-get...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
build-essential is already the newest version (12.1ubuntu2).
curl is already the newest version (7.47.0-1ubuntu2).
g++ is already the newest version (4:5.3.1-1ubuntu1).
gcc is already the newest version (4:5.3.1-1ubuntu1).
git is already the newest version (1:2.7.4-0ubuntu1).
lib32z1-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4).
libffi-dev is already the newest version (3.2.1-4).
liblua5.2-dev is already the newest version (5.2.4-1ubuntu1).
libxslt1-dev is already the newest version (1.1.28-2.1).
lua5.2 is already the newest version (5.2.4-1ubuntu1).
pkg-config is already the newest version (0.29.1-0ubuntu1).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
python-lxml is already the newest version (3.5.0-1build1).
python-setuptools is already the newest version (20.7.0-1).
tmux is already the newest version (2.1-3build1).
mercurial is already the newest version (3.7.3-1ubuntu1).
stow is already the newest version (2.2.2-1).
supervisor is already the newest version (3.2.0-2).
tnef is already the newest version (1.4.9-1).
libmysqlclient-dev is already the newest version (5.7.12-0ubuntu1.1).
libxml2-dev is already the newest version (2.9.3+dfsg1-1ubuntu0.1).
mysql-client is already the newest version (5.7.12-0ubuntu1.1).
mysql-server is already the newest version (5.7.12-0ubuntu1.1).
wget is already the newest version (1.17.1-1ubuntu1.1).
python-pip is already the newest version (8.1.1-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Ensuring libsodium version...
Ensuring redis version...
redis-2.8.17 installed.
Ensuring setuptools and pip versions...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by tenleftfingers** [comment]
Same issue on 16.04 64-bit desktop.

**Comment by bsnsk** [comment]
Same issue here

**Comment by transformatika** [comment]
Install pip 7.1.2 using command:
easy_install pip==7.1.2

**Comment by MathiasCiarlo** [comment]
I think this might be a memory issue, see [this stackoverflow link](http://stackoverflow.com/questions/24455238/lxml-installation-error-ubuntu-14-04-internal-compiler-error). I only had 512MB, I upgraded to 1GB, and it worked fine :)

**Comment by tenleftfingers** [comment]
I have 12GB. Maybe we are facing different issues with the same symptom then.

**Comment by klaszlo** [comment]
@tenleftfingers: have you tried `pip install --upgrade pip` ?
For me it solved, but not the exact same issue. (on Ubuntu 16.04.1 LTS)

**Comment by tenleftfingers** [comment]
Not sure @klaszlo but thanks for the tip. When they fix some other bugs I might try it again. The false notifications of unread mail have put me off for the time being.

**Comment by KakolIsSomewhatGay** [comment]
Getting the following error.

```

      _   _       _
     | \ | |_   _| | __ _ ___
     |  \| | | | | |/ _' / __|
     | |\  | |_| | | (_| \__ \
     |_| \_|\__, |_|\__,_|___/
            |___/

     This script installs dependencies for the Nylas Sync Engine.

     For more details, visit:
     https://www.github.com/nylas/sync-engine

Updating packages...
MySQL Exists. Not adding upstream mysql package
Installing dependencies from apt-get...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
g++ is already the newest version.
gcc is already the newest version.
lib32z1-dev is already the newest version.
libffi-dev is already the newest version.
pkg-config is already the newest version.
python-setuptools is already the newest version.
tmux is already the newest version.
python-pip is already the newest version.
stow is already the newest version.
supervisor is already the newest version.
tnef is already the newest version.
build-essential is already the newest version.
curl is already the newest version.
git is already the newest version.
libxml2-dev is already the newest version.
libxslt1-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-lxml is already the newest version.
wget is already the newest version.
liblua5.2-dev is already the newest version.
lua5.2 is already the newest version.
mercurial is already the newest version.
libmysqlclient-dev is already the newest version.
mysql-client is already the newest version.
mysql-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Ensuring libsodium version...
Ensuring redis version...
redis-2.8.17 installed.
Ensuring setuptools and pip versions...
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py", line 14, in <module>
    from ndg.httpsclient.subj_alt_name import SubjectAltName
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 102, in <module>
    class AnotherName(univ.Sequence):
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 105, in AnotherName
    namedtype.NamedType('value', univ.Any().subtype(
AttributeError: 'module' object has no attribute 'Any'
```

**Comment by grinich** [comment]
Closing due to stale and can't reproduce.
