### ISSUE TITLE
Messages api error:  NoneType' object has no attribute 'decrypt'

### ISSUE THREAD

**Issue by johnjjung** [nylas/sync-engine#321]
I'm getting this error only when I hit messages.

Anytime I hit `/messages/` or looking at messages.

This happened to me after I restarted the server. 

```
{
"message": "'NoneType' object has no attribute 'decrypt'",
"type": "api_error"
}
```

The inbox-api.log file I have shows this:

```
Exception on /messages [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/inbox/api/ns_api.py", line 373, in message_query_api
    return encoder.jsonify(messages)
  File "/vagrant/inbox/api/kellogs.py", line 428, in jsonify
    return Response(self.cereal(obj, pretty=True),
  File "/vagrant/inbox/api/kellogs.py", line 410, in cereal
    cls=self.encoder_class)
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/vagrant/inbox/api/kellogs.py", line 382, in default
    expand=expand, is_n1=is_n1)
  File "/vagrant/inbox/api/kellogs.py", line 42, in encode
    return _encode(obj, namespace_public_id, expand, is_n1=is_n1)
  File "/vagrant/inbox/api/kellogs.py", line 142, in _encode
    'body': obj.body,
  File "/vagrant/inbox/models/message.py", line 447, in body
    return decode_blob(self._compacted_body).decode('utf-8')
  File "/vagrant/inbox/security/blobstorage.py", line 48, in decode_blob
    compressed_plaintext = decryption_oracle.decrypt(body, scheme)
  File "/vagrant/inbox/security/oracles.py", line 171, in decrypt
    return self._secret_box.decrypt(ciphertext)
AttributeError: 'NoneType' object has no attribute 'decrypt'

{"exception": "Traceback (most recent call last):\n\t  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n\t  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n\t  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n\t  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n\t  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n\t  File \"/vagrant/inbox/api/ns_api.py\", line 373, in message_query_api\n    return encoder.jsonify(messages)\n\t  File \"/vagrant/inbox/api/kellogs.py\", line 428, in jsonify\n    return Response(self.cereal(obj, pretty=True),\n\t  File \"/vagrant/inbox/api/kellogs.py\", line 410, in cereal\n    cls=self.encoder_class)\n\t  File \"/usr/lib/python2.7/json/__init__.py\", line 250, in dumps\n    sort_keys=sort_keys, **kw).encode(obj)\n\t  File \"/usr/lib/python2.7/json/encoder.py\", line 209, in encode\n    chunks = list(chunks)\n\t  File \"/usr/lib/python2.7/json/encoder.py\", line 431, in _iterencode\n    for chunk in _iterencode_list(o, _current_indent_level):\n\t  File \"/usr/lib/python2.7/json/encoder.py\", line 332, in _iterencode_list\n    for chunk in chunks:\n\t  File \"/usr/lib/python2.7/json/encoder.py\", line 442, in _iterencode\n    o = _default(o)\n\t  File \"/vagrant/inbox/api/kellogs.py\", line 382, in default\n    expand=expand, is_n1=is_n1)\n\t  File \"/vagrant/inbox/api/kellogs.py\", line 42, in encode\n    return _encode(obj, namespace_public_id, expand, is_n1=is_n1)\n\t  File \"/vagrant/inbox/api/kellogs.py\", line 142, in _encode\n    'body': obj.body,\n\t  File \"/vagrant/inbox/models/message.py\", line 447, in body\n    return decode_blob(self._compacted_body).decode('utf-8')\n\t  File \"/vagrant/inbox/security/blobstorage.py\", line 48, in decode_blob\n    compressed_plaintext = decryption_oracle.decrypt(body, scheme)\n\t  File \"/vagrant/inbox/security/oracles.py\", line 171, in decrypt\n    return self._secret_box.decrypt(ciphertext)\n\tAttributeError: 'NoneType' object has no attribute 'decrypt'\n", "endpoint": "namespace_api.message_query_api", "account_id": 1, "level": "error", "timestamp": "2016-07-21T22:14:05.336323Z", "module": "inbox.api.srv:28", "greenlet_id": 140214786380336, "event": "Uncaught error thrown by Flask/Werkzeug"}
```

**Comment by johnjjung** [comment]
Not sure what happened but it looks like I might have been storing message on the machine...

in etc/config.json files, use "STORE_MESSAGES_ON_S3": true

And add:

"AWS_ACCESS_KEY_ID" : "",
"AWS_SECRET_ACCESS_KEY" : "",
"MESSAGE_STORE_BUCKET_NAME" : "",

Then it'll store all your messages on S3 so you won't lose them
