### ISSUE TITLE
Database can't update to commit 583401f

### ISSUE THREAD

**Issue by happydemic** [nylas/sync-engine#324]
Everything works fine using any commit up to 10 June 2016, but with 583401f and subsequent commits, inbox-start produces errors and the api won't start.

Running sudo sh setup.sh produces the following errors:
```
160725 18:59:52 mysqld_safe A mysqld process already exists
Setting up database: inbox
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:450: Warning: Can't create database 'inbox'; database exists
  cursor.execute(statement, parameters)
Already revisioned by alembic version: 29a1f2ef5653
Verifying database.
Finished setting up database.

Setting up database: inbox_1
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:450: Warning: Can't create database 'inbox_1'; database exists
  cursor.execute(statement, parameters)
Already revisioned by alembic version: 29a1f2ef5653
Verifying database.
Traceback (most recent call last):
  File "bin/create-db", line 85, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "bin/create-db", line 79, in main
    verify_db(engine, schema_name, int(key))
  File "/vagrant/inbox/ignition.py", line 187, in verify_db
    table, increment, key)
AssertionError: table: account, increment: 1, key: 1
```

**Comment by happydemic** [comment]
Fixed on the latest commit (with manual update of config.json): 

From ```sudo sh setup.sh```:
```
Copying default development configuration to /etc/inboxapp
Error: sync engine config is newer and merging of configs not (yet) supported.
Diffs:
src: ./etc/config-dev.json dest: /etc/inboxapp/config.json
51d50
< "REDIS_HOSTNAME": "localhost",
52a52
> "REDIS_SHARDS": ["localhost"],
77c77,80
< "UMPIRE_BASE_URL": "127.0.0.1"
---
> "UMPIRE_BASE_URL": "127.0.0.1",
> 
> "MAILGUN_DOMAIN": null,
> "MAILGUN_API_KEY": null
```
After I edited /etc/inboxapp/config.json to match /vagrant/etc/config-dev.json, I can now run both inbox-start and inbox-api. Thanks.
