### ISSUE TITLE
arcihve/delete/read actions not syncing to gmail accounts

### ISSUE THREAD

**Issue by audibleblink** [nylas/sync-engine#378]
I'm currently running the self-hosted version of of the sync-engine on linux from home. In order to access the sync-engine from outside the network on my laptop, I bind the server's 5555 port to my laptop's localhost with `ssh -L 5555:localhost:5555 $nylas_server` and the laptop client begins to receive emails like normal. When reading, archiving, and deleting mail, everything seems to be working fine locally, but none of those actions are actually reflected on gmail.com. I'm not seeing any errors in the activity window.

**Comment by caske33** [comment]
I'm experiencing the same issue using a VPS.

**Comment by trestletech** [comment]
Same symptoms but I'm getting errors like:

```
[ERROR] {"greenlet_id": xxx, "account_id": 3, "error_tb": "Traceback (most recent call last):\n\t  File \"/home/jeff/workspace/sync-engine/inbox/transactions/actions.py\", line 382, in execute_with_lock\n    self.func(*func_args)\n\t  File \"/home/jeff/workspace/sync-engine/inbox/actions/base.py\", line 50, in mark_unread\n    set_remote_unread(cri
spin_client, account_id, message_id, unread)\n\t  File \"/home/jeff/workspace/sync-engine/inbox/actions/backends/generic.py\", line 81, in set_remote_unread\n    not unread)\n\t  File \"/home/jeff/workspace/sync-engine/inbox/actions/backends/generic.py\", line 69, in _set_flag\n    crispin_client.conn.add_flags(uids, [flag_name], silent=True)\n\tTypeError: add
_flags() got an unexpected keyword argument 'silent'\n", "timestamp": "2016-09-20T20:49:38.004957Z", "error_message": "add_flags() got an unexpected keyword argument 'silent'", "provider": "fastmail", "module": "inbox.transactions.actions:404", "extra_args": {"unread": false}, "action": "mark_unread", "action_log_id": 100, "error": "TypeError", "record_id": 36
504, "level": "error", "event": "Uncaught error"}
[INFO] {"account_id": 3, "timestamp": "2016-09-20T20:49:38.016648Z", "module": "inbox.transactions.actions:421", "record_id": 36504, "greenlet_id": xxx, "duration": 30, "event": "Syncback task retrying action after sleeping", "level": "info", "extra_args": {"unread": false}, "action_log_id": 100, "action": "mark_unread"}
[ERROR] {"greenlet_id": 139654360882864, "account_id": 1, "error_tb": "Traceback (most recent call last):\n\t  File \"/home/jeff/workspace/sync-engine/inbox/transactions/actions.py\", line 382, in execute_with_lock\n    self.func(*func_args)\n\t  File \"/home/jeff/workspace/sync-engine/inbox/actions/base.py\", line 50, in mark_unread\n    set_remote_unread(cri
spin_client, account_id, message_id, unread)\n\t  File \"/home/jeff/workspace/sync-engine/inbox/actions/backends/generic.py\", line 81, in set_remote_unread\n    not unread)\n\t  File \"/home/jeff/workspace/sync-engine/inbox/actions/backends/generic.py\", line 69, in _set_flag\n    crispin_client.conn.add_flags(uids, [flag_name], silent=True)\n\tTypeError: add
_flags() got an unexpected keyword argument 'silent'\n", "timestamp": "2016-09-20T20:49:38.180193Z", "error_message": "add_flags() got an unexpected keyword argument 'silent'", "provider": "gmail", "module": "inbox.transactions.actions:404", "extra_args": {"unread": false}, "action": "mark_unread", "action_log_id": 26, "error": "TypeError", "record_id": 36484,
 "level": "error", "event": "Uncaught error"}
```

And sporadically

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/jeff/workspace/sync-engine/inbox/transactions/actions.py", line 456, in _run
    gevent.with_timeout(task.timeout(self.task_timeout), task.execute)
  File "/usr/local/lib/python2.7/dist-packages/gevent/timeout.py", line 253, in with_timeout
    return function(*args, **kwds)
  File "/home/jeff/workspace/sync-engine/inbox/transactions/actions.py", line 312, in execute
    task.execute_with_lock()
  File "/home/jeff/workspace/sync-engine/inbox/transactions/actions.py", line 427, in execute_with_lock
    gevent.sleep(self.retry_interval)
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 194, in sleep
    hub.wait(loop.timer(seconds, ref=ref))
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 630, in wait
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
Timeout: 60 seconds
<SyncbackWorker at 0x7f03d085d870> failed with Timeout

```

**Comment by exadeci** [comment]
I got a similar issue with Gmail, I delete a mail it disappears only to come back after the sync, I have to delete it on Gmail's web interface for it to work.
