### ISSUE TITLE
It went wrong when I run setup.sh

### ISSUE THREAD

**Issue by Stephen-Chen** [nylas/sync-engine#383]
```
vagrant@vagrant-ubuntu-precise-64:/vagrant$ sudo ./setup.sh 

      _   _       _
     | \ | |_   _| | __ _ ___
     |  \| | | | | |/ _' / __|
     | |\  | |_| | | (_| \__ \
     |_| \_|\__, |_|\__,_|___/
            |___/

     This script installs dependencies for the Nylas Sync Engine.

     For more details, visit:
     https://www.github.com/nylas/sync-engine

Updating packages...
MySQL Exists. Not adding upstream mysql package
Installing dependencies from apt-get...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
g++ is already the newest version.
gcc is already the newest version.
lib32z1-dev is already the newest version.
libffi-dev is already the newest version.
pkg-config is already the newest version.
python-setuptools is already the newest version.
tmux is already the newest version.
python-pip is already the newest version.
stow is already the newest version.
supervisor is already the newest version.
tnef is already the newest version.
build-essential is already the newest version.
curl is already the newest version.
git is already the newest version.
libxml2-dev is already the newest version.
libxslt1-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-lxml is already the newest version.
wget is already the newest version.
liblua5.2-dev is already the newest version.
lua5.2 is already the newest version.
mercurial is already the newest version.
libmysqlclient-dev is already the newest version.
mysql-client is already the newest version.
mysql-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Ensuring libsodium version...
Ensuring redis version...
redis-2.8.17 installed.
Ensuring setuptools and pip versions...
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py", line 14, in <module>
    from ndg.httpsclient.subj_alt_name import SubjectAltName
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 102, in <module>
    class AnotherName(univ.Sequence):
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 105, in AnotherName
    namedtype.NamedType('value', univ.Any().subtype(
AttributeError: 'module' object has no attribute 'Any'
```
How can I fix it?

**Comment by palandri** [comment]
Just passing by, I have exactly the same problem.

**Comment by Stephen-Chen** [comment]
see #382 
the same issue
