### ISSUE TITLE
pkg_resources.DistributionNotFound: 'inbox-sync'

### ISSUE THREAD

**Issue by cmoud94** [nylas/sync-engine#384]
After solving [#382](https://github.com/nylas/sync-engine/issues/382) I've got another problem while trying to start `/vagrant/bin/inbox-start`.

It should be said that I've changed vbox image from `ubuntu/precise64` to `debian/jessie64` as suggested in [#382](https://github.com/nylas/sync-engine/issues/382#issuecomment-240646956).

```
vagrant@jessie:/vagrant$ INBOX_ENV=dev ./bin/inbox-start 
Traceback (most recent call last):
  File "./bin/inbox-start", line 29, in <module>
    from inbox.mailsync.service import SyncService
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/vagrant/inbox/mailsync/service.py", line 13, in <module>
    from inbox.events.remote_sync import EventSync, GoogleEventSync
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/vagrant/inbox/events/remote_sync.py", line 18, in <module>
    from inbox.events.google import GoogleEventsProvider
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/vagrant/inbox/events/google.py", line 14, in <module>
    from inbox.auth.oauth import OAuthRequestsWrapper
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/vagrant/inbox/auth/__init__.py", line 17, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/vagrant/inbox/util/misc.py", line 182, in register_backends
    modules = load_modules(base_name, base_path)
  File "/vagrant/inbox/util/misc.py", line 168, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/vagrant/inbox/auth/generic.py", line 15, in <module>
    from inbox.sendmail.smtp.postel import SMTPClient
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/vagrant/inbox/sendmail/__init__.py", line 17, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/vagrant/inbox/util/misc.py", line 182, in register_backends
    modules = load_modules(base_name, base_path)
  File "/vagrant/inbox/util/misc.py", line 168, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/vagrant/inbox/sendmail/base.py", line 13, in <module>
    VERSION = pkg_resources.get_distribution('inbox-sync').version
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 535, in get_distribution
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 415, in get_provider
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 943, in require
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 829, in resolve
    
pkg_resources.DistributionNotFound: The 'inbox-sync' distribution was not found and is required by the application
```

Branch: master

**Comment by cmoud94** [comment]
Solved in [#382](https://github.com/nylas/sync-engine/issues/382). Closing issue.
