### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Any'

### ISSUE THREAD

**Issue by questmessage** [nylas/sync-engine#430]
Following the [The Nylas Sync Engine Installation and Setup instructions](https://github.com/nylas/sync-engine#installation-and-setup), I get the output below when I run step 7:

> 7. NYLAS_ENV=dev bin/inbox-start

```
vagrant@vagrant-ubuntu-precise-64:/vagrant$ NYLAS_ENV=dev bin/inbox-start
Traceback (most recent call last):
  File "bin/inbox-start", line 20, in <module>
    from inbox.config import config as inbox_config
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/inbox/__init__.py", line 1, in <module>
    from nylas import *
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nylas/__init__.py", line 11, in <module>
    from nylas.client.client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nylas/client/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nylas/client/client.py", line 2, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from ndg.httpsclient.ssl_peer_verification import SUBJ_ALT_NAME_SUPPORT
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/ssl_peer_verification.py", line 14, in <module>
    from ndg.httpsclient.subj_alt_name import SubjectAltName
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 102, in <module>
    class AnotherName(uni.Sequence):

  File "/usr/local/lib/python2.7/dist-packages/ndg/httpsclient/subj_alt_name.py", line 105, in AnotherName
    namedtype.NamedType('value', univ.Any().subtype(
AttributeError: 'module' object has no attribute 'Any'

```

..am new to this sort of installation..my background is node.js/mongodb & front-end development

**Comment by kun-zhou** [comment]
Maybe related to #427 ?

**Comment by itsjef** [comment]
You have to manually install `pyasn1`

`pip install -U pyasn1`
