### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4uOsu9/imapclient/

### ISSUE THREAD

**Issue by cclam0827** [nylas/sync-engine#456]
Does anyone have this issue??? I cannot use after i run `vagrant up`.

```
==> default: dist-packages/pkg_resources/__init__.py", line 851, in resolve
==> default:         dist = best[req.key] = env.best_match(req, ws, installer)
==> default:       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1116, in best_match
==> default:         dist = working_set.find(req)
==> default:       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 714, in find
==> default:         raise VersionConflict(dist, req)
==> default:     pkg_resources.VersionConflict: (chardet 2.0.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('chardet<3.1.0,>=3.0.2'))
==> default:     Error in atexit._run_exitfuncs:
==> default:     Traceback (most recent call last):
==> default:       File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
==> default:         func(*targs, **kargs)
==> default:       File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
==> default:         info('process shutting down')
==> default:     TypeError: 'NoneType' object is not callable
==> default:     Error in atexit._run_exitfuncs:
==> default:     Traceback (most recent call last):
==> default:       File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
==> default:         func(*targs, **kargs)
==> default:       File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
==> default:         info('process shutting down')
==> default:     TypeError: 'NoneType' object is not callable
==> default:     Error in atexit._run_exitfuncs:
==> default:     Traceback (most recent call last):
==> default:       File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
==> default:         func(*targs, **kargs)
==> default:       File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
==> default:         info('process shutting down')
==> default:     TypeError: 'NoneType' object is not callable
==> default:     Error in sys.exitfunc:
==> default:     Traceback (most recent call last):
==> default:       File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
==> default:         func(*targs, **kargs)
==> default:       File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
==> default:         info('process shutting down')
==> default:     TypeError: 'NoneType' object is not callable
==> default:
==> default:     ----------------------------------------
==> default: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4uOsu9/imapclient/
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by morenofa** [comment]
I have the same error, how I can solve it? 
Thanks!

**Comment by TimKraemer** [comment]
Your log says:
`pkg_resources.VersionConflict: (chardet 2.0.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('chardet<3.1.0,>=3.0.2'))`
that means, you need `chardet` in a version between `3.0.2` and `3.1.0`. You can install it by typing the following line in within your setup environment:
`sudo pip install -I chardet==3.0.2`
